version: '3.8'

services:
  adso-chat-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: adso-chat-backend:latest
    networks:
      - mynetwork
    container_name: adso-chat-backend
    ports:
      - "8080:8080"
    stdin_open: true # Corresponds to -i in `docker run`
    tty: true        # Usually needed alongside stdin_open to keep the container running
    restart: unless-stopped  # Ensures the container restarts if it stops for any reason other than being manually stopped


  adso-chat-ollama:
    build:
      context: ollama
      dockerfile: Dockerfile
    image: adso-chat-ollama
    networks:
      - mynetwork
    container_name: adso-chat-ollama
    ports:
      - "11434:11434"
    volumes:
      - type: bind
        source: ./data
        target: /data
    restart: unless-stopped


  adso-ui:
   build:
     context: frontend
     dockerfile: Dockerfile
   image: adso-ui
   networks:
    - mynetwork
   container_name: adso-ui
   ports:
    - "80:80"
   restart: unless-stopped

volumes:
    ollama_data:
networks:
  mynetwork:
    driver: bridge

