package cloud.isaura.llama3.model;

import java.util.Objects;



/**
 * Represents the response from various types of models, including language, chat, embedding, and moderation models.
 * This class encapsulates the generated content, token usage statistics, and finish reason.
 *
 * @param <T> The type of content generated by the model.
 */
public class Response<T> {

    private final T content;
    private final TokenUsage tokenUsage;


    /**
     * Create a new Response.
     *
     * <p>Will contain {@code null} {@code TokenUsage} and {@code FinishReason}</p>
     *
     * @param content the content to wrap.
     */
    public Response(T content) {
        this(content, null);
    }

    /**
     * Create a new Response.
     *
     * @param content the content to wrap.
     * @param tokenUsage the token usage statistics, or {@code null}.

     */
    public Response(T content, TokenUsage tokenUsage) {
        this.content = content;
        this.tokenUsage = tokenUsage;

    }

    /**
     * Get the content.
     * @return the content.
     */
    public T content() {
        return content;
    }

    /**
     * Get the token usage statistics.
     * @return the token usage statistics, or {@code null}.
     */
    public TokenUsage tokenUsage() {
        return tokenUsage;
    }

    /**
     * Get the finish reason.
     * @return the finish reason, or {@code null}.
     */


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Response<?> that = (Response<?>) o;
        return Objects.equals(this.content, that.content)
                && Objects.equals(this.tokenUsage, that.tokenUsage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(content, tokenUsage);
    }

    @Override
    public String toString() {
        return "Response {" +
                " content = " + content +
                ", tokenUsage = " + tokenUsage +

                " }";
    }

    /**
     * Create a new Response.
     * @param content the content to wrap.
     * @return the new Response.
     * @param <T> the type of content.
     */
    public static <T> Response<T> from(T content) {
        return new Response<>(content);
    }

    /**
     * Create a new Response.
     * @param content the content to wrap.
     * @param tokenUsage the token usage statistics.
     * @return the new Response.
     * @param <T> the type of content.
     */
    public static <T> Response<T> from(T content, TokenUsage tokenUsage) {
        return new Response<>(content, tokenUsage);
    }


}
